# Generated by Django 5.1.1 on 2024-10-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_images_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='filter_price',
        ),
        migrations.DeleteModel(
            name='Filter_Price',
        ),
    ]
